name: CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e-commerce:
    # 0. النظام المطلوب
    runs-on: ubuntu-latest

    steps:
      # 1. نسخ الكود
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. تنصيب Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3. شغل الكونتينرات
      - name: Build and Run with Docker Compose
        run: |
          NODE_ENV=development APP_REPLICAS=1 docker-compose up --build -d

      # 4. شغل الاختبارات داخل الكونتينر
      - name: Run tests
        run: docker exec -it e-commerce-container npm run test

      # 5. إيقاف وتنظيف الكونتينرات
      - name: Stop services
        run: docker compose down -v
